server:
  port: 8888
 
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      default-filters:
        #This is to prevent two different cors headers being sent.
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
      - id: account
        uri: lb://ACCOUNT
        predicates:
        - Path=/account/**
        # filters:
        # - AddResponseHeader=Access-Control-Allow-Origin, *
      - id: schedule
        uri: lb://SCHEDULE
        predicates:
        - Path=/schedule/**
        # filters:
        # - AddResponseHeader=Access-Control-Allow-Origin, *
      - id: course
        uri: lb://COURSE
        predicates:
        - Path=/course/**
        # filters:
        # - AddResponseHeader=Access-Control-Allow-Origin, *